# number_agents: 2
# pieces:
# - !!python/tuple [2.4, 0.3]
# - !!python/tuple [1.3, -3.2]
# - !!python/tuple [-1.5, -2.9]
# - !!python/tuple [-1.0, -2.3]
# radius: 0.5

# number_agents: 2
# pieces:
# - !!python/tuple [-2.0, -1.0]
# - !!python/tuple [-3.0, -4.0]
# radius: 0.5

number_agents: 2
pieces:
- !!python/tuple [-2.8, -3.05]
- !!python/tuple [2.2, -2.2]
- !!python/tuple [2.15, -2.3]
- !!python/tuple [2.35, -0.45]
- !!python/tuple [-3.0, -2.1]
- !!python/tuple [-3.7, -3.1]
- !!python/tuple [-1.05, -3.05]
- !!python/tuple [-1.15, -3.1]
- !!python/tuple [-2.55, -2.9]
- !!python/tuple [2.6, -1.1]
- !!python/tuple [1.8, -0.1]
- !!python/tuple [2.6, -0.2]
- !!python/tuple [1.75, -3.35]
- !!python/tuple [3.0, -0.15]
- !!python/tuple [1.85, -3.2]
- !!python/tuple [-2.85, -1.45]
- !!python/tuple [2.2, -1.75]
- !!python/tuple [-0.2, -3.3]
- !!python/tuple [0.6, 0.1]
- !!python/tuple [2.45, -2.8]
- !!python/tuple [-2.9, -3.4]
- !!python/tuple [-4.0, -2.5]
- !!python/tuple [2.3, -2.2]
- !!python/tuple [-2.6, -2.6]
- !!python/tuple [-0.75, -3.3]
- !!python/tuple [-1.85, -3.5]
- !!python/tuple [2.15, -1.65]
- !!python/tuple [-2.95, -2.65]
- !!python/tuple [-2.65, -2.6]
- !!python/tuple [2.5, -1.8]
- !!python/tuple [2.7, -1.9]
- !!python/tuple [3.15, -1.6]
- !!python/tuple [-1.7, -2.9]
- !!python/tuple [1.7, -2.8]
- !!python/tuple [2.2, -0.4]
- !!python/tuple [2.05, -2.5]
- !!python/tuple [-3.35, -3.45]
- !!python/tuple [2.5, -0.8]
- !!python/tuple [-2.3, -3.5]
- !!python/tuple [-1.2, -3.3]
- !!python/tuple [2.3, -1.8]
- !!python/tuple [1.5, -0.15]
- !!python/tuple [-2.75, -3.3]
- !!python/tuple [-2.25, -2.8]
- !!python/tuple [-3.85, -2.35]
- !!python/tuple [-2.9, -3.05]
- !!python/tuple [-2.4, -1.4]
- !!python/tuple [-3.2, -3.4]
- !!python/tuple [-1.1, -3.05]
- !!python/tuple [2.9, -2.35]
radius: 0.5