# number_agents: 2
# pieces:
# - !!python/tuple [2.4, 0.3]
# - !!python/tuple [1.3, -3.2]
# - !!python/tuple [-1.5, -2.9]
# - !!python/tuple [-1.0, -2.3]
# radius: 0.5

number_agents: 2
pieces:
- !!python/tuple [-3.3, -1.4]
- !!python/tuple [-1.45, 2.85]
- !!python/tuple [-1.3, 2.9]
# - !!python/tuple [-0.3, 2.45]
# - !!python/tuple [-2.8, -2.35]
# - !!python/tuple [-0.05, 1.8]
# - !!python/tuple [-1.75, -2.25]
# - !!python/tuple [-3.1, 2.05]
# - !!python/tuple [0.2, 2.75]
# - !!python/tuple [-3.6, -1.05]
# - !!python/tuple [-3.4, 1.55]
# - !!python/tuple [-2.5, -2.65]
# - !!python/tuple [-1.35, -2.65]
# - !!python/tuple [-2.8, -2.85]
# - !!python/tuple [-2.25, -3.1]
# - !!python/tuple [-3.25, 0.65]
# - !!python/tuple [-1.5, -2.6]
# - !!python/tuple [-1.9, -3.35]
# - !!python/tuple [-3.15, 1.05]
# - !!python/tuple [-3.0, -2.65]
# - !!python/tuple [-1.85, 3.0]
# - !!python/tuple [0.2, 2.6]
# - !!python/tuple [-2.6, 2.85]
# - !!python/tuple [-0.45, 2.4]
# - !!python/tuple [-2.4, 2.4]
# - !!python/tuple [-3.1, -1.65]
# - !!python/tuple [-3.5, -3.45]
# - !!python/tuple [-3.25, -2.1]
# - !!python/tuple [-2.5, -2.2]
# - !!python/tuple [-2.5, -3.35]
# - !!python/tuple [-2.7, -3.4]
# - !!python/tuple [-2.45, -4.1]
# - !!python/tuple [-2.5, -4.6]
# - !!python/tuple [0.1, 1.6]
# - !!python/tuple [-1.25, 2.5]
# - !!python/tuple [-3.5, -1.4]
# - !!python/tuple [-0.9, 2.4]
# - !!python/tuple [0.05, 1.4]
# - !!python/tuple [-3.55, -1.7]
# - !!python/tuple [-3.35, 2.25]
# - !!python/tuple [-0.8, 2.1]
# - !!python/tuple [-2.8, 2.95]
# - !!python/tuple [-3.35, -3.3]
# - !!python/tuple [-2.3, -2.45]
# - !!python/tuple [-1.2, 2.5]
# - !!python/tuple [-3.45, -3.5]
# - !!python/tuple [-3.2, -2.35]
# - !!python/tuple [-0.75, 2.95]
# - !!python/tuple [-0.2, 2.8]
# - !!python/tuple [-1.25, -2.65]
radius: 0.5